### ISSUE TITLE
Remove CanLoader documentation?

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/documentation#113]
I think that old iCub users (see https://github.com/robotology/icub-tech-support/issues/1129) are used to canLoader, and they should just switch to the new FirmwareUpdater.  However, the documentation is a bit not clear w.r.t. to the canLoader, as there is still a first level link to canLoader in the main firmware page (see https://icub-tech-iit.github.io/documentation/icub_firmware/) and also in the firmware https://icub-tech-iit.github.io/documentation/icub_firmware/firmware/firmware/ . Furthermore, there is a full page of docs in https://icub-tech-iit.github.io/documentation/icub_firmware/canLoader/canLoader/, that starts with a small warning message "Canloader is deprecated since this PR" . However, this may be misleading, as the CanLoader  tool was not just deprecated in that PR (approximately one year ago), but it was completely removed. 

To avoid confusion, could it make sense to just delete the old canLoader docs? If we need any info from it, we can always recovere it from the git history or the wiki history.

**Comment by amaroyo** [comment]
thank you @traversaro for the "old iCub users"..... :joy:

**Comment by traversaro** [comment]
Thanks @pattacini , I think it is much more clear now.
