### ISSUE TITLE
Clarify section of `user-env`

### ISSUE THREAD

**Issue by Uboldi80** [icub-tech-iit/documentation#141]
The section to review is https://icub-tech-iit.github.io/documentation/icub_operating_systems/icubos/user-env/#required-configuration.

@traversaro

**Comment by traversaro** [comment]
In particular, it seems (unless I am wrong) that `OBJ_SUBDIR` is already set in the `.bashrc_iCub`  file, so we can avoid changing it unless specific workflows (not documented in this docs) are required: https://github.com/icub-tech-iit/icub-os-files/search?q=OBJ_SUBDIR .

**Comment by pattacini** [comment]
cc @mbrunettini
