### ISSUE TITLE
Clarify what "skip in case of iCub Server" means

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/documentation#143]
It is not clear what "skip in case of iCub Server" means in https://icub-tech-iit.github.io/documentation/icub_operating_systems/other-machines/generic-machine/#icub-software-repository-and-common-package.

With @Uboldi80 we were setting up a iCub Server Laptop and we were not sure if we had to skip it.

**Comment by traversaro** [comment]
The link prints https://icub-tech-iit.github.io/documentation/icub_operating_systems/other-machines/icub-server-laptop/#software-repositories .

**Comment by traversaro** [comment]
This probably requires https://github.com/icub-tech-iit/documentation/issues/142 to be solved before working on this.

**Comment by pattacini** [comment]
cc @mbrunettini 
As @traversaro said, to be addressed along with #142.

**Comment by traversaro** [comment]
As https://github.com/icub-tech-iit/documentation/issues/142 evolved a bit, now this is issue is basically a subset of https://github.com/icub-tech-iit/documentation/issues/142, so I think we can close it.
