### ISSUE TITLE
Document process of configuring the YARP server in the iCub setup?

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/documentation#155]
While debugging the iCubNancy01, I noticed that in our documentation it is not documented anywhere the fact that a single machine in the system should be designated to host the yarpserver, and all the other machines should be configured, first aligning the `yarp namespace`, and then setting the server address via `yarp detect --write` or `yarp conf ip socketport`. Not sure if this should be added.

**Comment by pattacini** [comment]
It would be a good addition indeed.

**Comment by traversaro** [comment]
fyi @Uboldi80
