### ISSUE TITLE
Add missing info on ele and wiring kits to Upperarm Covers UKIT

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/documentation#16]
The Upperam Covers UKIT documentation lacks the required information about the missing sub-kits (`ele` and `wiring`), which have been already added into our management system.

cc @Elio75 @Fabrizio69 @salvi-mattia @MrAndrea

**Comment by Elio75** [comment]
In the documentation made # 495, I think we could add the respective codes to WKIT and EKIT in the Ukit table and what they contain, it seems to me that these also form part of the whole assembly of the upgrade upper arm cover?

![134](https://user-images.githubusercontent.com/53298662/86596762-0f8daa80-bf9b-11ea-942c-f41d84be5ba1.PNG)

**Comment by pattacini** [comment]
Yes indeed @Elio75, would you be willing to amend the documentation then?
Just do what we've done together via fork and pull-request.

**Comment by Elio75** [comment]
Ok i will do it as soon as possible

**Comment by Elio75** [comment]
I added in the UKIT table of documentation the EKIT_004 and WKIT_004 with its respective contents.
I await the return of Emiliano Barbieri to make me give some pictures of the covers with all the electronics mounted.

![4](https://user-images.githubusercontent.com/53298662/87416668-51d46e80-c5cf-11ea-897d-b5160a78ea8c.PNG)
![5](https://user-images.githubusercontent.com/53298662/87416675-53059b80-c5cf-11ea-8f1f-cf486fa0dc19.PNG)

**Comment by pattacini** [comment]
Cool thanks @Elio75 👍 
We'll be awaiting the final PR then.

**Comment by pattacini** [comment]
PR merged: see #27 🚀
