### ISSUE TITLE
Document/clarify existence of iCub version 1.7

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/documentation#176]
The documentation on iCub arm kinematics report slighly different values for the "1.7" arm, see https://icub-tech-iit.github.io/documentation/icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-arms/ . However, in https://icub-tech-iit.github.io/documentation/icub_versions/ there is no documentation for iCub 1.7 .

**Comment by maggia80** [comment]
I didn't know the existence of arm 1.7.

**Comment by pattacini** [comment]
We do have it, actually.
Our codebase mirrors it: see for example https://github.com/robotology/icub-main/blob/master/src/libraries/iKin/src/iKinFwd.cpp#L1699.

**Comment by traversaro** [comment]
According to robots-configuration files, the following robots have v1.7 arms (https://github.com/robotology/robots-configuration/search?q=left_v1.7):
* `iCubParis01`
* `iCubHertfordshire01`
* `iCubGenova03`
