### ISSUE TITLE
Missing screws in the MKIT_004 - iCub, Upperarms, fix skin breaking (mechanics)

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/documentation#21]
MKIT004 on WinGST is not compliant with iCub Tech Docs (missing screws):

![image](https://user-images.githubusercontent.com/12031391/87651091-e5827800-c752-11ea-87de-ae0038d4869a.png)

![image](https://user-images.githubusercontent.com/12031391/87650829-8de40c80-c752-11ea-973d-9763aaec072a.png)

**Comment by salvi-mattia** [comment]
FIXED
![immagine](https://user-images.githubusercontent.com/43994292/89403634-e76ba580-d718-11ea-9d12-dee7ce608ce3.png)
