### ISSUE TITLE
Leg Cabling: Replacing the cable 14

### ISSUE THREAD

**Issue by jhielson** [icub-tech-iit/documentation#247]
Hi everyone,

I need help replacing a cable in the iCub robot. The crimp part of the cable 14 snapped today during an experiment. Following your documentation, there is a white cover over the joint that needs to be removed to access the cable. In my robot, I can see the white cover but the free space between the legs (Photo 26: https://icub-tech-iit.github.io/documentation/icub_tendons/waist_legs/#31-hip-flexion-cable-14 ) does not exist. There are a lot of cables and a metallic part with the tag OB4 in this area. Can you please give some guidance on how to remove those parts so I can replace the cable?

![icub](https://user-images.githubusercontent.com/2223912/214919038-9bf5d11e-8bb9-4f9d-8565-c19ef9c858ed.jpeg)

**Comment by pattacini** [comment]
Hi @jhielson 

This is not the proper repo where to ask for assistance. Would you mind opening a ticket on https://github.com/robotology/icub-tech-support instead?
