### ISSUE TITLE
Document installation procedure for ergocub-head system

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/documentation#282]
During the ICRA 2023 demo with ergoCub, one problem that hit us is that we wanted to debug a software problem on the ergocub-head, but it is not clear how the software was installed there. While the software installation on the ergocub-torso basically reflects the one tipically used in icub-head, so documented in:
* https://icub-tech-iit.github.io/documentation/icub_operating_systems/icubos/installation-from-scratch/
* https://icub-tech-iit.github.io/documentation/sw_installation/icub_head_superbuild/

At the moment instead the ergocub-head has some specificies that I am not sure if they are documented anywhere:
* Use of robotology-superbuild compiled against conda-forge dependencies to support ROS humble on Ubuntu 20.04
* Use of GPU-enabled librealsense
* Something else that I may be missing

It would be great to have even a simple documentation on how to setup the system in its intendend state from scratch.

**Comment by pattacini** [comment]
>Use of robotology-superbuild compiled against conda-forge dependencies to support ROS humble on Ubuntu 20.04

This will be no longer true.

>Use of GPU-enabled librealsense

This still holds, but we may simply point to an official doc for that.

**Comment by pattacini** [comment]
First proposal available at:
- https://github.com/icub-tech-iit/documentation/pull/318

**Comment by pattacini** [comment]
The PR has been merged @martinaxgloria. Well done 🎉
