### ISSUE TITLE
Update coupling parameters for Hand MK5.1

### ISSUE THREAD

**Issue by xEnVrE** [icub-tech-iit/documentation#307]
Today, while reviewing the newly opened PR https://github.com/icub-tech-iit/ergocub-software/pull/169, I had the chance to compare the [documented](https://icub-tech-iit.github.io/documentation/hands/hands_mk5_coupling/#mk51-coupling-variables) parameters of the coupling law for the MK5 **.1** hand and a table that can be found in https://github.com/icub-tech-iit/ergocub-design-lowerarm/issues/157#issuecomment-1674984233.

It seems that there are discrepancies for the following paremeters.

**Note:** green and yellow highlighed text is just coming from the screenshot of the "table" indicated above. I am not highlighting anything. 

Moreover please take into account that for each "table" entry the order of numbers is "thumb", "index" and "pinky" (as index == middle == ring) while each "documentation" entry report all the 5 parameters in the order "thumb", "index", "middle", "ring", "pinky".

# Parameter $q_{0off}$

### table
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/248f78ce-74e3-4d2c-916f-12f3692e0174)

### documentation

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/f42c97cf-2a98-4cdc-9bb5-fb7e6f6836ff)

# Parameter $k$

### table

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/8f106586-85e6-4c5c-b5f1-ad7ea6ec5e02)

### documentation

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/8e4c1bc1-eb7d-48c1-8fda-b8d5c6de7ae4)

# Parameter $d$

### table

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/8ed02e8c-50da-4e1b-b524-d5e30cb2390a)

### documentation

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/91fe3cf6-2bab-476b-be8f-96ef24bcf630)

# Parameter $l$

### table
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/a1627125-80c9-4284-85ba-2e673c0a8135)

### documentation
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/a261a17f-52af-4ae0-a261-57ad0b949157)

# Parameter $b$

### table

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/bcbc529b-9cd8-404f-8eae-9542b0852751)

### documentation
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/2638c377-ded2-43fc-900d-ff359fa2f4f0)

# Parameter $s$

### table
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/f0f74f2a-f457-4b36-a429-28e31ef5826f)

### documentation
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/cc0139d0-3ee2-4a6c-a790-b5084fb312ee)

# Parameter $t$

### table
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/a3c97228-5c8a-45b0-aeb0-fd48baf16b61)

### documentation
![image](https://github.com/icub-tech-iit/documentation/assets/6014499/54a1cdbf-7f48-46ed-a3ac-d5c39e2e1ddb)

# Parameter $f$

### table

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/349e6282-df0f-4f82-8706-1de21b5f94b9)

### documentation

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/84ac5c48-7e18-4251-8b63-9e36196d5dcb)

# Paramter $r$

### table

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/91569647-fd27-44ad-958e-deb4cd2abfce)

### documentation

![image](https://github.com/icub-tech-iit/documentation/assets/6014499/161ffa57-0237-4e36-80e9-33b14166273f)

cc @pattacini

**Comment by pattacini** [comment]
cc @fiorisi @Lawproto

**Comment by Lawproto** [comment]
@xEnVrE a small disclaimer. The excel file only served me to update the documentation, it should not be considered official. The values you screenshotted were reported to me from @ale-git as a double-check, are in `m` instead of `mm` and I do not exactly know how they have been calculated when there is some difference with the one I measured via CAD (yellow highlight). In general, I considered the difference small enough and I put the value coming from the CAD inside the documentation.

However, I just noticed that for the single letter length parameters I accidentally copied the Mk5.0 parameters instead of putting the correct one. I thank you for pointing this out, I will proceed with an update via PR.

**Comment by xEnVrE** [comment]
Thanks for the clarification @Lawproto. 

Indeed I though they were not super official but the parameters were the same as `Mk 5.0`, as you said, hence I though it was important to notify that as it seemed very strange to me. 

Moreover while I was conducting experiments on Gazebo, in order to study the length of the fingers, I have also asked some numbers to @ale-git and they were very different from those of the documentation, hence I was kinda sure that something was wrong.

**Comment by Lawproto** [comment]
PR opened. 
https://github.com/icub-tech-iit/documentation/pull/312
