### ISSUE TITLE
Revert #328

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/documentation#336]
After an internal discussion during our board meeting, we decided to revert PR #328.

This is because the convention for the CSYS is limited to the alignment of their axes wrt a resting position of the robot, but doesn't include the directions of rotation. In practical terms, this means that the same joint angles guarantee a specular symmetry between the arms.

Reverting #328 is as simple as clicking a button, although we may need to carry out a careful review.

cc @Lawproto @Nicogene @fiorisi @traversaro

**Comment by Nicogene** [comment]
I opened a PR with just the commit reverted:
- https://github.com/icub-tech-iit/documentation/pull/341

But it seems not sufficient, more refinement is needed.

**Comment by pattacini** [comment]
A gentle reminder for @Lawproto.
cc @Nicogene

**Comment by Lawproto** [comment]
@pattacini there you go:
- https://github.com/icub-tech-iit/documentation/pull/345

**Comment by pattacini** [comment]
Thanks!
