### ISSUE TITLE
Update the Battery documenation

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/documentation#342]
After the changes decided here https://github.com/robotology/icub-firmware/issues/476#issuecomment-1980593096 in order to satisfy this request https://github.com/icub-tech-iit/tickets/issues/3343,

we need to update the documentation accordingly.

**Dod**

Documentation updated

**Comment by MSECode** [comment]
I've updated the branch aligning what decided on the fw and sw side and fixing the timing that were wrong with respect to the code. 
Please, @valegagge, take a look to it and if it looks good to you I'll open the PR together with the others for the sw and fw.
