### ISSUE TITLE
Unable to find some datasheet of the geaboxes mounted on ergoCubV1_*

### ISSUE THREAD

**Issue by GiulioRomualdi** [icub-tech-iit/documentation#359]
Hi, I was looking for the datasheets of the gearboxes mounted on the `ergoCubV1_*` model. I found them on [this](https://icub-tech-iit.github.io/documentation/ergoCub1/ergoCub1-joints/) webpage. 

I tried to look at the datasheet of the gearboxes online but had some problems finding the datasheet for some joints. Here is a table with the datasheets I found

| Joint | Geabox of the documentation | Datasheet |
|:-----:|:---------------------------:|:---------:|
|Joint 0 - shoulder pitch | CSD-20-100-2UH | [🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-20-100-2uh) |
| Joint 1 - shoulder roll | CSD-17-100-2A | [🟠 I assume is this one](https://www.harmonicdrive.net/products/component-sets/cup-type/csd-2a/csd-17-100-2a-r) even if this model I linked is the CSD-17-100-2A-R while the one in the documentation is CSD-17-100-2A |
| Joint 2 - shoulder yaw | CSD-17-100-2UH | [🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-17-100-2uh) |
| Joint 3 - elbow | CSD-17-100-2A | [🟠 I assume is this one](https://www.harmonicdrive.net/products/component-sets/cup-type/csd-2a/csd-17-100-2a-r) even if this model I linked is the CSD-17-100-2A-R while the one in the documentation is CSD-17-100-2A |
| Joint 0 - torso roll | CSD-20-100-2UH | [🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-20-100-2uh) |
| Joint 1 - torso pitch | CSD-20-160-2UH | 🔴 This gearbox does not seem to exist [these are the gearboxes of the family CSD-2UH](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh) |
| Joint 2 - torso yaw | CSD-20-100-2UH |[🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-20-100-2uh) |
| Joint 0 - hip pitch | CSD-25-100-2UH | [🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-25-100-2uh) |
| Joint 1 - hip roll | CSD-20-160-2UH | 🔴 This gearbox does not seem to exist [these are the gearboxes of the family CSD-2HU](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh) | 
| Joint 2 - hip yaw | CSD-20-100-2UH | [🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-20-100-2uh) |
| Joint 3 - knee | CSD-25-100-2UH | [🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-25-100-2uh) |
| Joint 4 - ankle pitch | CSD-25-100-2UH | [🟢 here](https://www.harmonicdrive.net/products/gear-units/gear-units/csd-2uh/csd-25-100-2uh) |
| Joint 5 - ankle roll | CSD-17-160-2A | 🔴  This gearbox does not seem to exist [these are the gearboxes of the family CSD-2A](https://www.harmonicdrive.net/products/component-sets/cup-type/csd-2a) | 

Could you help me in finding the missing part? I opened the issue here since there might be a problem with the documentation. 
Linking the datasheets in the documentation could also be beneficial.

cc @pattacini and @traversaro

**Comment by traversaro** [comment]
Probably also @fiorisi may know something about this.

**Comment by GiulioRomualdi** [comment]
With @fabiobergonti we checked the cad and the `Joint 1 - hip roll`	is CSD-20-160-2UH. The only info we found is on this website https://innodrive.ru/en/catalog/harmonic/gear/9342/. 

Ho the other hand for `CSD-17-160-2A` we found this datasheet  https://harmonicdrive.de/fileadmin/Downloads/Getriebe_Katalog/Harmonic_Drive_Gears_EN_1053522.pdf 
and as it can be seen in the picture the gearbox is not available 
![image](https://github.com/user-attachments/assets/b71280ba-46ca-4b13-8e58-d2a877eca645)

**Comment by GiulioRomualdi** [comment]
We also checked the elbow and the shoulder roll `CSD-17-100-2A` similar to https://github.com/icub-tech-iit/documentation/issues/359#issuecomment-2343262188 the datasheet is here https://harmonicdrive.de/fileadmin/Downloads/Getriebe_Katalog/Harmonic_Drive_Gears_EN_1053522.pdf

![image](https://github.com/user-attachments/assets/b850a518-1ece-4a75-8545-8d4629877678)


So in the end the main problem is related to `CSD-17-160-2A` which does not exist in the datasheet

**Comment by FabioBergonti** [comment]
We tried to look for the cad of `CSD-17-160-2A` in https://harmonicdrive.partcommunity.com/3d-cad-models/csd-2a-harmonic-drive-gear-component-sets-harmonic-drive?info=harmonicdrive%2Fgetriebe_einbausaetze%2Fcsd_2a_asmtab.prj&cwid=6555 but it's not available
![image](https://github.com/user-attachments/assets/d9dd26b6-f8fc-4402-9f6b-8e65c9f1ffe0)

**Comment by GiulioRomualdi** [comment]
with @fabiobergonti we went to the warehouse and we found the harmonic driver. The documentation is correct. The piece exists. 
![20240911_142000 (1)](https://github.com/user-attachments/assets/7b3bb922-1d72-4a89-a690-1f810363c49c)

**Comment by fiorisi** [comment]
@GiulioRomualdi I try give a complete explanation even if I have seen that you already found some answers.

The website that you are referring to, namely `harmonicdrive.net`, belongs to the US group Harmonic Drive LLC. 
For our geographical location we refer instead to Harmonic Drive SE (Germany), which has a different website `harmonicdrive.de` and sligthly different products.

For example, if I am not mistaken, the product CSD-20-160-2UH can be found on the [German catalogue](https://harmonicdrive.de/fileadmin/Downloads/Getriebe_Katalog/Harmonic_Drive_Gears_EN_1053522.pdf) (see page 163).

![image](https://github.com/user-attachments/assets/c66bcac2-3b3e-4bee-8204-83afa72ffeb8)

Can you double check with the German catalogue if there are still differences? 

Concerning the series `2A`, I think that we didn't include `-R` because this suffix changes depending on the size of the HD (decision probably taken decades ago).

Finally, for the the part `CSD-17-160-2A`, this is a special harmonic drive that can not be found on the catalogue.

![image](https://github.com/user-attachments/assets/ead738f8-ec6d-4eb9-91b4-ac80bdfd7006)

**Comment by GiulioRomualdi** [comment]
Thank you! So as far as I understood CSD-17-160-2A has been built ad hoc for us.

**Comment by pattacini** [comment]
We can probably close this issue but I'm open to accepting PR to improve the documentation.
