### ISSUE TITLE
Mismatch bewteen the ankle roll	motor model of robots configuration and the documentation.

### ISSUE THREAD

**Issue by GiulioRomualdi** [icub-tech-iit/documentation#360]
I was checking the motors model mounted on ergoCubSN001 and the one in the documentation https://icub-tech-iit.github.io/documentation/ergoCub1/ergoCub1-joints/

| Mismatch | Joint | Motor in the documentation | Motor in robots-config | Link of robots-config |
|:---:|:---:|:----:|:-----------------------:|:----:|
|🟢  | shoulder pitch | MOOG_C2900576 | MOOG-BL-C2900576 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/left_arm-eb2-j0_1-mec.xml) |
| 🟢 | shoulder roll | MOOG_C2900576 | MOOG-BL-C2900576 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/left_arm-eb2-j0_1-mec.xml) |
| 🟢 | shoulder yaw | MOOG_C2900575 | MOOG-BL-C2900575 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/left_arm-eb4-j2_3-mec.xml)  |
| 🟢 | elbow | MOOG_C2900575 | MOOG-BL-C2900575 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/left_arm-eb4-j2_3-mec.xml) |
| 🟢 | torso roll | MOOG_C2900576 | MOOG_C2900576 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/torso-eb5-j0_2-mec.xml) |
| 🟢 | torso_pitch | MOOG_C2900576 | MOOG_C2900576 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/torso-eb5-j0_2-mec.xml)   |
|  🟢| torso yaw | MOOG_C2900576 | MOOG_C2900576 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/torso-eb5-j0_2-mec.xml)  |
| 🟢 | hip pitch | MOOG_C2900580 | MOOG_C2900580 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/right_leg-eb6-j0_3-mec.xml) |
| 🟢 | hip roll | MOOG_C2900576 |MOOG_C2900576  | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/right_leg-eb6-j0_3-mec.xml) | 
| 🟢 | hip yaw | MOOG_C2900576 | MOOG_C2900576 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/right_leg-eb6-j0_3-mec.xml) |
| 🟢 | knee | MOOG_C2900580 | MOOG_C2900580 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/right_leg-eb6-j0_3-mec.xml) |
| 🟢  | ankle pitch | MOOG_C2900580 | MOOG_C2900580 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/right_leg-eb7-j4_5-mec.xml) |
| :x: | ankle roll | MOOG_C2900576 | MOOG_C2900575 | [here](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/hardware/mechanicals/right_leg-eb7-j4_5-mec.xml) |

Which is the correct model mounted on the robot?

**Comment by GiulioRomualdi** [comment]
cc @isorrentino @giulero @traversaro @pattacini

**Comment by pattacini** [comment]
cc @fiorisi

**Comment by pattacini** [comment]
I'll update the robots conf files accordingly then.

**Comment by pattacini** [comment]
> I'll update the robots conf files accordingly then.

See https://github.com/robotology/robots-configuration/pull/678.

I've applied the same fix to all the ergoCub robots, blindly. If this is not correct, I'll change the PR. Let me know @fiorisi

**Comment by pattacini** [comment]
> I've applied the same fix to all the ergoCub robots, blindly. If this is not correct, I'll change the PR. Let me know @fiorisi

Verified with @fiorisi: all ergoCub robots mount the same ankle motor.
