### ISSUE TITLE
Rotating iCub GIFs  affects menu readability

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/documentation#6]
On my laptop, the rotating iCub GIFs in the main menu affects the readability of the menu:
![icub_rotating_menu](https://user-images.githubusercontent.com/1857049/83323010-10c10e80-a25c-11ea-8cb5-4d3d26228123.gif)

I would personally remove it, but perhaps there is a specific reason for which the GIF was placed there. 

@marcoaccame

**Comment by pattacini** [comment]
I had the same impression. We can remove it for improving readability.

**Comment by pattacini** [comment]
Fixed in https://github.com/icub-tech-iit/documentation/commit/f6f43c88de75a5706525106ebfe6e344f3337ec9.
