### ISSUE TITLE
Substitute old tendon docs with a link to the new docs?

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/documentation#7]
If I search "iCub tendons" on Google, I get a link to some rather old and broken wiki pages: 
* http://wiki.icub.org/wiki/Tendons_and_replacement
* http://wiki.icub.org/wiki/Assembly_instructions

Probably it could make sense to remove those old pages and just substitute them with links to https://icub-tech-iit.github.io/documentation/icub_tendons/ ? 

cc @pattacini @julijenv @violadelbono

**Comment by pattacini** [comment]
Definitely @traversaro 👍 
I'll do that!

Thanks for crawling the internet!

**Comment by pattacini** [comment]
Done.
