### ISSUE TITLE
Improve documentation on network configurations to connect laptop to EMS board

### ISSUE THREAD

**Issue by isorrentino** [icub-tech-iit/documentation#80]
I needed to connect my laptop to the motor setup in DIC area and I discovered that we do not have public and official documentation on how to do it. In particular, I discovered that I had to set a static IP address and a certain subnet mask to the network interface to be able to communicate with the EMS board. This information is not anywhere and future users could experience problems in setting up the correct configuration.
cc @traversaro

**Comment by traversaro** [comment]
Some useful network docs are provided in https://icub-tech-iit.github.io/documentation/icub_firmware/firmware/firmware/#the-topology-of-the-robot , but indeed the subnet mask is not listed there nor in any of the `network.<YARP_ROBOT_NAME>.xml` files referenced. Probably that could be a good point in which to add a reference to the subnet mask used, what do you think @davidetome ?

**Comment by davidetome** [comment]
@traversaro I take this in charge 📝

cc @pattacini

**Comment by traversaro** [comment]
Thanks @davidetome !

**Comment by davidetome** [comment]
Done, please see this [PR](https://github.com/icub-tech-iit/documentation/pull/83)
