### ISSUE TITLE
change title for "configure-static-ip"

### ISSUE THREAD

**Issue by mbrunettini** [icub-tech-iit/documentation#85]
The title for the page https://icub-tech-iit.github.io/documentation/configure_static_ip/configure-static-ip/
can be very misleading, please specify better that this case applies ONLY to EMS communication

**Comment by pattacini** [comment]
@davidetome could you please have a look at this?

**Comment by davidetome** [comment]
> The title for the page https://icub-tech-iit.github.io/documentation/configure_static_ip/configure-static-ip/
> can be very misleading, please specify better that this case applies ONLY to EMS communication

@mbrunettini It is clearly specified in the doc description content at top of the page  that the doc applies to all ETH boards (not only EMS); anyway I'm going to change the title too 👍🏻 

cc @pattacini

**Comment by mbrunettini** [comment]
Sure, BUT I was referring to the title shown on the left navigation bar, at that level is very _visible_ and  can be misleading

**Comment by davidetome** [comment]
done in this [PR](https://github.com/icub-tech-iit/documentation/pull/87)
